FROM node:14-alpine3.12

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./

RUN npm install -g nodemon 

RUN npm install  

COPY . . 

HEALTHCHECK --interval=60s --timeout=2s --retries=3 CMD wget localhost:5003/ -q -O - > /dev/null 2>&1

CMD [ "npm","run","dev"]

EXPOSE 5001