FROM node:14-alpine3.12

RUN apk update && apk add --no-cache curl vim wget bash nano

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./

RUN npm install -g nodemon 

RUN npm install  

COPY . . 

HEALTHCHECK --interval=60s --timeout=2s --retries=3 CMD wget localhost:5000/ -q -O - > /dev/null 2>&1

CMD [ "npm","run","dev"]

EXPOSE 5000